#%RAML 1.0
title: BountySports API Documentation
baseUri: https://bountysports.com/
version: 1.0

/users/update_user_refer_code:
  displayName: Update user refer code
  post:
    description: Update user refer code
    responses:
      200:
        body:
          application/json:

/users/get_refer_reward_money:
  displayName: Get refer reward money
  post:
    description: Get refer reward money
    responses:
      200:
        body:
          application/json:

/users/update_refer_reward_money:
  displayName: Update refer reward money
  post:
    description: Update refer reward money
    body:
      application/json:
        type: |
          {
            "type": "object",
            "properties": {
              "reward_money": {
                "type": "number",
                "required": true
              }
            }
          }
        example: |
          {
            "reward_money": 100
          }
    responses:
      200:
        body:
          application/json:

/users/send_otp:
  displayName: Send user OTP code
  post:
    description: Send user OTP code
    body:
      application/json:
        type: |
          {
            "type": "object",
            "properties": {
              "email": {
                "type": "string",
                "required": true
              },
              "otp": {
                "type": "number"
              }
            }
          }
        example: |
          {
            "email": "john.doe@email.com",
            "otp": 4587
          }
    responses:
      200:
        body:
          application/json:

/users/register:
  displayName: Register a new user
  post:
    description: Register a new user. Requires recaptcha pass
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/register_manual:
  displayName: Register a new user manually
  post:
    description: Register a new user manually
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/login:
  displayName: User login
  post:
    description: User login
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/adminlogin:
  displayName: Admin user login
  post:
    description: Admin user login
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/verifyotpadmin:
  displayName: Verify admin user otp
  post:
    description: Verify admin user otp
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/verifyotp:
  displayName: Verify user otp
  post:
    description: Verify user otp
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/resendotp:
  displayName: Resend OTP code
  post:
    description: Resend OTP code
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/checksocialid:
  displayName: Check user social id
  post:
    description: Check user social id
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/sociallogin:
  displayName: Social login
  post:
    description: Social login
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/myprofile:
  displayName: Get user profile
  post:
    description: Get user profile
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/updateprofile:
  displayName: Update user profile
  post:
    description: Update user profile
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/changepassword:
  displayName: Change user password
  post:
    description: Change user password
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/forgetpassword:
  displayName: Send forgot password code
  post:
    description: Send forgot password code
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/getbalance:
  displayName: Get user balance
  post:
    description: Get user balance
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/addbalanceadmin:
  displayName: Add admin balance
  post:
    description: Add admin balance
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/addbalance:
  displayName: Add user balance
  post:
    description: Add user balance
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/transactions:
  displayName: Get transactions
  post:
    description: Get transactions
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/getbankdetails:
  displayName: Get bank details
  post:
    description: Get bank details
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/savebankdetails:
  displayName: Save bank details
  post:
    description: Save bank details
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/updatebankdetails:
  displayName: Update bank details
  post:
    description: Update bank details
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/withdrawal:
  displayName: Generate withdrawal request
  post:
    description: Generate withdrawal request
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/mywithdrawalrequests:
  displayName: Get a user's withdrawal requests
  post:
    description: Get a user's withdrawal requests
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/withdrawalrequests:
  displayName: Get all users withdrawal requests
  post:
    description: Get all users withdrawal requests
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/approvewithdrawal:
  displayName: Approve withdrawal
  post:
    description: Approve withdrawal
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/rejectwithdrawal:
  displayName: Reject withdrawal
  post:
    description: Reject withdrawal
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/alltransactions:
  displayName: Get all transactions
  post:
    description: Get all transactions
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/allusers:
  displayName: Get all users
  post:
    description: Get all users
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/usersbyid:
  displayName: Get user by id
  post:
    description: Get user by id
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/downloadtransactions:
  displayName: Download transactions
  post:
    description: Download transactions
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/downloadusers:
  displayName: Download users
  post:
    description: Download users
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/downloadwithdrawalrequests:
  displayName: Download withdrawal requests
  post:
    description: Download withdrawal requests
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/dashboard:
  displayName: Get dashboard data
  post:
    description: Get dashboard data
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/saveleads:
  displayName: Save leads
  post:
    description: Save leads
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/sendsupportmail:
  displayName: Send support mail
  post:
    description: Send support mail
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/removeuserflag:
  displayName: Remove user flag
  post:
    description: Remove user flag
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/blockunblockuser:
  displayName: Block user
  post:
    description: Block user
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/checkusernamesignup:
  displayName: Check if usernames exist before signup
  post:
    description: Check if usernames exist before signup
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/checkusernameoremail:
  displayName: Check username or email if exists
  post:
    description: Check username or email if exists
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/checkusernameeditprofile:
  displayName: Check user can edit profile
  post:
    description: Check user can edit profile
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/getreferredusers:
  displayName: Get referred users
  post:
    description: Get referred users
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/getpromocodes:
  displayName: Get promo codes
  post:
    description: Get promo codes
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/addpromocode:
  displayName: Add promo code
  post:
    description: Add promo code
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/editpromocode:
  displayName: Edit promo code
  post:
    description: Edit promo code
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/getcommunicationpref:
  displayName: Get communication preference
  post:
    description: Get communication preference
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/editcommunicationpref:
  displayName: Edit communication preference
  post:
    description: Edit communication preference
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/updateappusetime:
  displayName: Update app use time
  post:
    description: Update app use time
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/users/acceptnewterms:
  displayName: Accept new terms
  post:
    description: Accept new terms
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/sports/getall:
  displayName: Get all sports
  post:
    description: Get all sports
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/matches/getmatchbysports:
  displayName: Get match by sports
  post:
    description: Get match by sports
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/matches/getmatchbypgasports:
  displayName: Get match by pga sports
  post:
    description: Get match by pga sports
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/matches/updateMatchResultAdmin:
  displayName: Update match result by admin
  post:
    description: Update match result by admin
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/matches/editmatchodds:
  displayName: Edit match odds
  post:
    description: Edit match odds
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/contests/selection_made:
  displayName: Make contest selection
  post:
    description: Make contest selection
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/contests/getcontestusersadmin:
  displayName: Get contest users for admin
  post:
    description: Get contest users for admin
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/contests/getmacthesbycontestadmin:
  displayName: Get matches by contest for admin
  post:
    description: Get matches by contest for admin
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/contests/updatecontestuserpointadmin:
  displayName: Update contest user point for admin
  post:
    description: Update contest user point for admin
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/contests/createcontest:
  displayName: Create contest
  post:
    description: Create contest
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/contests/getupcomingcontest:
  displayName: Get upcoming contest
  post:
    description: Get upcoming contest
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/contests/getfeaturedcontest:
  displayName: Get featured contest
  post:
    description: Get featured contest
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/contests/single:
  displayName: Get single contest
  post:
    description: Get single contest
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/contests/contestmatchdetails:
  displayName: Get contest match details
  post:
    description: Get contest match details
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/contests/joincontest:
  displayName: Join test
  post:
    description: Join test
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/contests/editcontestmatches:
  displayName: Edit contest matches
  post:
    description: Edit contest matches
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/contests/leaderboard:
  displayName: Get leader board
  post:
    description: Get leader board
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/contests/getlivecontest:
  displayName: Get live contests
  post:
    description: Get live contests
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/contests/getpastcontest:
  displayName: Get past contests
  post:
    description: Get past contests
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/contests/downloadpastcontestadmin:
  displayName: Download past contests for admin
  post:
    description: Download past contests for admin
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/contests/getlivecontestadmin:
  displayName: Get live contests for admin
  post:
    description: Get live contests for admin
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/contests/getpastcontestadmin:
  displayName: Get past contests for admin
  post:
    description: Get past contests for admin
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/contests/getupcomingcontestadmin:
  displayName: Get upcoming contests by admin
  post:
    description: Get upcoming contests by admin
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/contests/singleadmin:
  displayName: Get single contest for admin
  post:
    description: Get single contest for admin
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/contests/deletecontest:
  displayName: Delete contest
  post:
    description: Delete contest
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/contests/publishcontest:
  displayName: Publish contest
  post:
    description: Publish contest
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/contests/featurethecontest:
  displayName: Feature contest
  post:
    description: Feature contest
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/contests/unfeaturethecontest:
  displayName: Unfeature contest
  post:
    description: Unfeature contest
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/contests/endContestAdmin:
  displayName: End contest for admin
  post:
    description: End contest for admin
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/cms/savehomepagecontent:
  displayName: Save home page content
  post:
    description: Save home page content
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/cms/uploadbase64:
  displayName: Upload base64
  post:
    description: Upload base64
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/cms/gethomepagecontent:
  displayName: Get homepage content
  post:
    description: Get homepage content
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/cms/gethowtoplaypagecontent:
  displayName: Get how to play page content
  post:
    description: Get how to play page content
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/cms/savehowtoplaypagecontent:
  displayName: Save how to play page content
  post:
    description: Save how to play page content
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/cms/getsimplepagecontent:
  displayName: Get simple play page content
  post:
    description: Get simple play page content
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/cms/savesimplepagecontent:
  displayName: Save simple page content
  post:
    description: Save simple page content
    body:
      application/json:
    responses:
      200:
        body:
          application/json:

/cms/short-url:
  /{code}:
    displayName: Get how to play page content
    post:
      description: Get how to play page content
      body:
        application/json:
      responses:
        200:
          body:
            application/json:

/cms/appversion:
  displayName: Get appversion
  post:
    description: Get appversion
    body:
      application/json:
    responses:
      200:
        body:
          application/json:
